FROM node:18 AS builder

WORKDIR /usr/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

RUN npm run build 

FROM node:18 AS production

WORKDIR /usr/app

COPY --from=builder /usr/app/dist ./dist
COPY package.json ./
COPY package-lock.json ./

RUN npm install --only=production

EXPOSE 5555

CMD ["node", "dist/shared/infra/http/server.js"]
