version: "3.7"

services:
  eletric_invoices_db:
    image: postgres
    container_name: eletric_invoices_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=eletric_invoices_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "eletric_invoices_db", "-U", "docker", "-d", "eletric_invoices_db", "-p", "5432", "-t", "5"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: eletric_invoices
    ports:
      - 5555:5555
    volumes:
      - .:/usr/app
      - /usr/src/app/node_modules

    depends_on:
      eletric_invoices_db:
        condition: service_healthy

volumes:
  pgdata:
    driver: local
